---
version: 2.1

debian-steps: &debian-steps
  steps:
    - checkout
    - run: ci/circleci-build-debian.sh
    - run: sh -c "ldd  build/app/*/lib/opencpn/*.so"
    - run: cd build; /bin/bash < upload.sh
    - run: python3 ci/git-push

jobs:
  build-macos:
    macos:
      xcode: "11.0.0"
    environment:
      - OCPN_TARGET: macos
    steps:
      - checkout
      - restore_cache:
          keys:
            - macos-cache-v1-{{checksum "ci/circleci-build-macos.sh"}}
      - run: ci/circleci-build-macos.sh
      - save_cache:
          key: macos-cache-v1-{{checksum "ci/circleci-build-macos.sh"}}
          paths:
            - /usr/local/Homebrew
            - /usr/local/Caskroom
            - /usr/local/Cellar
            - /usr/local/lib
            - /usr/local/include
      - run: sh -c "otool -L build/app/*/OpenCPN.app/Contents/PlugIns/*.dylib"
      - run: cd build; /bin/bash < upload.sh
      - run: python3 ci/git-push

  build-xenial:
    docker:
      - image: circleci/buildpack-deps:xenial-scm
    environment:
      - OCPN_TARGET: xenial
      - USE_DEADSNAKES_PY37: 1
    <<: *debian-steps

  build-bionic:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    environment:
      - OCPN_TARGET: bionic
    <<: *debian-steps

  build-bionic-gtk3:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    environment:
      - BUILD_GTK3: true
      - OCPN_TARGET: bionic-gtk3
    <<: *debian-steps

  build-focal:
    docker:
      - image: circleci/buildpack-deps:focal-scm
    environment:
      - OCPN_TARGET: focal
    <<: *debian-steps

  build-buster:
    docker:
      - image: circleci/buildpack-deps:buster-scm
    environment:
      - OCPN_TARGET: buster
    <<: *debian-steps

std-filters: &std-filters
  filters:
    branches:
      ignore:
        - tmp
        - /tmp-.*/

workflows:
  version: 2
  build_all:
    jobs:
      - build-macos:
          <<: *std-filters

      - build-xenial:
          <<: *std-filters

      - build-bionic-gtk3:
          <<: *std-filters

      - build-bionic:
          <<: *std-filters

      - build-focal:
          <<: *std-filters

      - build-buster:
          <<: *std-filters
